plugins:
  topic_group_button_enabled:
    default: true
    client: true
  topic_group_button_url:
    default: "https://www.discourse.org"
    client: true
  topic_group_button_title:
    default: "Button description here.."
    client: true
  topic_group_button_label:
    default: "Click Me"
    client: true
  topic_group_button_allowed_group:
    default: "trust_level_4"
    client: true
